export const SECURITY_DEPOSITS_CONSTANTS = {
  MODULE_NAME: 'SUPERADMIN_SECURITY_DEPOSITS',
  ERRORS: {
    SECURITY_DEPOSIT_NOT_FOUND: 'SecurityDeposit not found.',
  },
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
};
