export const EXPENSE_CATEGORIES_CONSTANTS = {
  MODULE_NAME: 'ADMIN_EXPENSE_CATEGORIES',
  ERRORS: {
    EXPENSE_CATEGORY_NOT_FOUND: 'ExpenseCategory not found.',
  },
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
};
