export const WHATSAPP_TEMPLATES_CONSTANTS = {
  MODULE_NAME: 'SUPERADMIN_WHATSAPP_TEMPLATES',
  ERRORS: {
    WHATS_APP_TEMPLATE_NOT_FOUND: 'WhatsAppTemplate not found.',
  },
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
};
