export const DAILY_SETTLEMENTS_CONSTANTS = {
  MODULE_NAME: 'SUPERADMIN_DAILY_SETTLEMENTS',
  ERRORS: {
    DAILY_SETTLEMENT_NOT_FOUND: 'DailySettlement not found.',
  },
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
};
